### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by CHHHAN** [Art-Ev/addon-snapserver#2]
Home Assistant 2023.10.1
Supervisor 2024.03.0
Operating System 11.4

![微信图片_20240327110727](https://github.com/Art-Ev/addon-snapserver/assets/52941464/11699963-f7fc-4dea-936c-9417adc3e7d2)

Updata Home Assistant ?

**Comment by n8ohu** [comment]
I'm getting this same error on 2024.4.0, except for the error code, which in my case is 101.

**Comment by CHHHAN** [comment]
About HomeAssistant OS install snapserver other way.
1. Add store https://github.com/alexbelgium/hassio-addons
2. Install Portainer
3. Enter portainer, add container with docker imgage: sweisgerber/snapcast:latest
BUT IS CAN NOT SETTING volumes path!!

**Comment by Art-Ev** [comment]
@CHHHAN & @n8ohu : should be fixed now, just had to update docker base image version. Just retry to install 😉
