### ISSUE TITLE
Cannot install add-on: unknown error (but is installed anyway if one waits long enough)

### ISSUE THREAD

**Issue by gpayer** [Art-Ev/addon-snapserver#3]
My current versions:

Core 2024.5.4
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

HW: Raspberry 4

Installation of this add-on takes a really long time, then fails with an unknown error. However CPU usage after this error message is still very high, so I chose to wait and see.

So after slightly over 15 minutes the add-on was installed and could be started as well. I assume with such a long installation time it runs into some timeout in HAOS.

Maybe it would be a good idea to move some of the more time consuming setup parts into the add-on container itself? This way the installation could take a normal amount of time without this confusing and potentially dangerous error. E.g. what happens if the user clicks "install" again?

**Comment by gpayer** [comment]
I see that the build process for librespot is the problematic part. The needed version 0.4.2 is already in the apk repository, so it might be worthwhile to test if it can be used directly.
It would reduce the installation time dramatically.

**Comment by ben-harack** [comment]
I saw the same issue (and the same cause) when I installed this add-on just now.

**Comment by Art-Ev** [comment]
@gpayer & @ben-harack : it's done 😉 Installation should take less time
