### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by barecool** [Art-Ev/addon-snapserver#4]
im onHA
Core 2024.9.2
Supervisor 2024.09.1
Operating System13.1
Frontend 20240909.1

`
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 cargo=1.71.1-r0 git=2.40.1-r0 protobuf-dev=3.21.12-r2 pulseaudio-dev=16.1-r10 && apk add --no-cache pulseaudio=16.1-r10 && apk add --no-cache librespot --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing && apk del --no-cache --purge .build-dependencies && rm -fr /tmp/* ~/.cargo /usr/.crates.toml /usr/.crates2.json' returned a non-zero code: 2
`

**Comment by Sciddie** [comment]
Got the same error a few minutes ago...

**Comment by brian-mckinney** [comment]
I did too

**Comment by Sciddie** [comment]
I edited the Dockerfile and now it works if you add my Fork as a repo in add-ons and install it from there:

https://github.com/Sciddie/addon-snapserver

It's dirty and I won't continue updating the fork, but for now it should work as expected.
Please write if you find any upcomming errors. I will fix them, as long as no official new Version comes.

**Comment by barecool** [comment]
yeah i did some updates of my own to get it to work - with the current versions that work with each other as well as I updated the base image
