### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by alexbennett123** [Art-Ev/addon-snapserver#5]
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 cargo=1.71.1-r0 git=2.40.1-r0 protobuf-dev=3.21.12-r2 pulseaudio-dev=16.1-r10 && apk add --no-cache pulseaudio=16.1-r10 && apk add --no-cache librespot --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing && apk del --no-cache --purge .build-dependencies && rm -fr /tmp/* ~/.cargo /usr/.crates.toml /usr/.crates2.json' returned a non-zero code: 2

**Comment by markus99** [comment]
Seeing the same

**Comment by Art-Ev** [comment]
Hi @alexbennett123, @markus99 : should be good now (hard to keep addons up to date at the speed at which HA is updated :P)
